language: node_js
os: linux
dist: focal
node_js:
  - "13.12.0"
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
jobs:
  include:
    # all branches
    - stage: Development - Lint, Test, & Build
      if: branch != master
      script:
        - yarn lint
        - yarn test
        - yarn generate
    # master branch only
    - stage: Production(master) - Lint, Test, Build, Upload coverage, Deploy to gh-pages
      if: branch = master
      script:
        - yarn lint
        - yarn test
        - yarn generate:gh-pages
        - npm install -g codecov
        - bash <(curl -s https://codecov.io/bash)
      deploy:
          provider: pages
          strategy: git
          skip_cleanup: true
          # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
          token: $GH_TOKEN
          target_branch: gh-pages
          local_dir: dist
          on:
            branch: master