# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Push Master

on:
  push:
    branches:
      - 'master'

jobs:
  deployment:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Setup Node and Install Depedencies
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn --frozen-lockfile

    - name: Lint and Test
      run: |
        yarn lint
        yarn test

    - name: Generate Github Pages
      run: yarn generate:gh-pages

    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        flags: unittests, master, push # optional

    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.