# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development - Lint, Test, and Generate

on:
  push:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master
  pull_request:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  lint-test-generate-build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Lint, Test, Build, Generate
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        yarn --frozen-lockfile
        yarn lint
        yarn test
        yarn build
        yarn generate
        yarn generate:gh-pages

    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        flags: unittests, dev # optional